name: vrc daily uploader
on:
  #push:
  #  branches:
  #    - main 
  #schedule:
  #  - cron: '0 14 * * *' #23:00(JST)に実行
  workflow_dispatch:
env:
  BUCKET_NAME : "my-video-vrc"
  AWS_REGION : "ap-northeast-1"
  API_KEY : ${{ secrets.API_KEY }}
  USER_ID : ${{ secrets.USER_ID }}
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  daily-s3-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up go 1.21.4
        uses: actions/setup-go@v4
        with:
            go-version: '1.21.4'
      - name: get flickr photo
        run: go run main.go
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy file to s3
        run: |
          aws s3 cp image1.jpg s3://${{ env.BUCKET_NAME }}/
          aws s3 cp image2.jpg s3://${{ env.BUCKET_NAME }}/
          aws s3 cp image3.jpg s3://${{ env.BUCKET_NAME }}/
